services:
  db:
    image: postgres:14
    container_name: pay_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - pay-network


  pay_fastapi:
    build: ./
    container_name: test_pay
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/pay_db/5432; do sleep 1; done; alembic upgrade head  && uvicorn backend.main:app --reload --host 0.0.0.0 --port 8000'
    volumes:
      - .:/app
    ports:
      - "8010:8000"
    restart: always
    env_file:
      - .env

    networks:
      - pay-network
volumes:
  postgres_data:



networks:
  pay-network:
    driver: bridge
